<a href="https://colab.research.google.com/github/Meatlf/LAB/blob/master/Pytorch/tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [0]:
x = torch.empty(5, 3)
print(x)

tensor([[1.7974e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix:



In [0]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6397, 0.4231, 0.8169],
        [0.9908, 0.3605, 0.9291],
        [0.6521, 0.9793, 0.8204],
        [0.3446, 0.4892, 0.8085],
        [0.1033, 0.6436, 0.4486]])


Construct a matrix filled zeros and of dtype long:



In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [0]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.0727, -0.2418, -0.8953],
        [ 1.3336, -1.3618,  0.3682],
        [-0.3112,  0.4077,  0.2255],
        [-1.8402, -0.4036, -0.4757],
        [-0.1126, -1.1743, -1.0218]])


Get its size:



In [0]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [0]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.1265,  0.1690, -0.0923],
        [ 1.4699, -1.2805,  0.4636],
        [-0.0853,  0.6237,  0.2560],
        [-1.6913,  0.0033,  0.2916],
        [ 0.7794, -0.5801, -0.2822]])


Addition: syntax 2



In [0]:
print(torch.add(x, y))

tensor([[-0.1265,  0.1690, -0.0923],
        [ 1.4699, -1.2805,  0.4636],
        [-0.0853,  0.6237,  0.2560],
        [-1.6913,  0.0033,  0.2916],
        [ 0.7794, -0.5801, -0.2822]])


Addition: providing an output tensor as argument



In [0]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.1265,  0.1690, -0.0923],
        [ 1.4699, -1.2805,  0.4636],
        [-0.0853,  0.6237,  0.2560],
        [-1.6913,  0.0033,  0.2916],
        [ 0.7794, -0.5801, -0.2822]])


Addition: in-place



In [0]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.1265,  0.1690, -0.0923],
        [ 1.4699, -1.2805,  0.4636],
        [-0.0853,  0.6237,  0.2560],
        [-1.6913,  0.0033,  0.2916],
        [ 0.7794, -0.5801, -0.2822]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [0]:
print("x:")
print(x)
print("\n")

print("x[:, 0]:")
print(x[:, 0]) 
print("\n")

print("x[:, 1]:")
print(x[:, 1]) 
print("\n")

x:
tensor([[-0.2546, -2.1409, -0.1851,  0.9679],
        [-0.6693,  1.0593,  1.4274, -0.5120],
        [-1.1988, -0.4282, -0.5412, -0.3887],
        [-0.9143, -0.0767, -0.8813,  0.7076]])


x[:, 0]:
tensor([-0.2546, -0.6693, -1.1988, -0.9143])


x[:, 1]:
tensor([-2.1409,  1.0593, -0.4282, -0.0767])




Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [0]:
x = torch.randn(4, 4)
print(x)
print("\n")
y = x.view(16)
print(y)
print("\n")
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

tensor([[ 1.4693,  2.4447,  1.7806, -0.9468],
        [ 0.0674, -0.0333, -0.5250,  0.8646],
        [-1.5991, -1.1130, -1.3248, -0.3086],
        [ 0.2551,  1.4613, -0.0225,  1.5430]])


tensor([ 1.4693,  2.4447,  1.7806, -0.9468,  0.0674, -0.0333, -0.5250,  0.8646,
        -1.5991, -1.1130, -1.3248, -0.3086,  0.2551,  1.4613, -0.0225,  1.5430])


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.4230])
1.4230009317398071


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [0]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
b = a.numpy()
print(b)

See how the numpy array changed in value.



In [0]:
a.add_(1)
print(a)
print(b)

Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!