<a href="https://colab.research.google.com/github/Meatlf/LAB/blob/master/PyTorch/tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix:



In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3202, 0.9479, 0.4532],
        [0.8204, 0.7232, 0.5231],
        [0.9037, 0.2556, 0.8253],
        [0.3308, 0.3970, 0.5722],
        [0.0349, 0.3849, 0.3721]])


Construct a matrix filled zeros and of dtype long:



In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.4035, -1.4330, -0.7647],
        [-0.3564, -1.3759,  0.2197],
        [ 0.9576, -0.3695, -0.0897],
        [-1.1422, -0.0755,  0.8263],
        [-1.1017, -0.1432, -0.4894]])


Get its size:



In [9]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.5659, -0.8353,  0.2045],
        [ 0.1011, -0.8638,  0.6536],
        [ 1.1351,  0.0907,  0.4673],
        [-0.9871,  0.2350,  1.4739],
        [-0.5758,  0.3955, -0.3644]])


Addition: syntax 2



In [11]:
print(torch.add(x, y))

tensor([[ 0.5659, -0.8353,  0.2045],
        [ 0.1011, -0.8638,  0.6536],
        [ 1.1351,  0.0907,  0.4673],
        [-0.9871,  0.2350,  1.4739],
        [-0.5758,  0.3955, -0.3644]])


Addition: providing an output tensor as argument



In [12]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.5659, -0.8353,  0.2045],
        [ 0.1011, -0.8638,  0.6536],
        [ 1.1351,  0.0907,  0.4673],
        [-0.9871,  0.2350,  1.4739],
        [-0.5758,  0.3955, -0.3644]])


Addition: in-place



In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.5659, -0.8353,  0.2045],
        [ 0.1011, -0.8638,  0.6536],
        [ 1.1351,  0.0907,  0.4673],
        [-0.9871,  0.2350,  1.4739],
        [-0.5758,  0.3955, -0.3644]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [14]:
print("x:")
print(x)
print("\n")

print("x[:, 0]:")
print(x[:, 0]) 
print("\n")

print("x[:, 1]:")
print(x[:, 1]) 
print("\n")

x:
tensor([[-0.4035, -1.4330, -0.7647],
        [-0.3564, -1.3759,  0.2197],
        [ 0.9576, -0.3695, -0.0897],
        [-1.1422, -0.0755,  0.8263],
        [-1.1017, -0.1432, -0.4894]])


x[:, 0]:
tensor([-0.4035, -0.3564,  0.9576, -1.1422, -1.1017])


x[:, 1]:
tensor([-1.4330, -1.3759, -0.3695, -0.0755, -0.1432])




Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [15]:
x = torch.randn(4, 4)
print(x)
print("\n")
y = x.view(16)
print(y)
print("\n")
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

tensor([[-0.4533, -0.2083, -0.0097,  0.5168],
        [-0.0384, -0.7657, -0.4717, -0.9248],
        [ 1.0815,  0.6098,  1.9231,  1.7882],
        [ 0.6045, -0.2546, -0.0214,  0.5986]])


tensor([-0.4533, -0.2083, -0.0097,  0.5168, -0.0384, -0.7657, -0.4717, -0.9248,
         1.0815,  0.6098,  1.9231,  1.7882,  0.6045, -0.2546, -0.0214,  0.5986])


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5027])
0.5027287602424622


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [21]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.5027], device='cuda:0')
tensor([1.5027], dtype=torch.float64)
