# [PyTorch 的 backward 为什么有一个 grad_variables 参数?](https://zhuanlan.zhihu.com/p/29923090)

In [1]:
import torch

In [2]:
from torch.autograd import Variable

In [3]:
x = Variable(torch.randn(3), requires_grad=True)
y = Variable(torch.randn(3), requires_grad=True)
z = Variable(torch.randn(3), requires_grad=True)

In [5]:
print(x)
print(y)
print(z)

tensor([-0.9992,  1.8910,  0.4474], requires_grad=True)
tensor([ 0.2450, -1.2913,  2.2724], requires_grad=True)
tensor([ 0.0119, -0.6289,  0.0733], requires_grad=True)


In [6]:
t = x + y

In [7]:
l = t.dot(z)

In [8]:
l.backward(retain_graph=True)
print(x.grad)
print(y.grad)
print(z)

tensor([ 0.0119, -0.6289,  0.0733])
tensor([ 0.0119, -0.6289,  0.0733])
tensor([ 0.0119, -0.6289,  0.0733], requires_grad=True)


In [9]:
print(z.grad)
print(t)

tensor([-0.7541,  0.5998,  2.7198])
tensor([-0.7541,  0.5998,  2.7198], grad_fn=<AddBackward0>)


In [10]:
x.grad.data.zero_()
y.grad.data.zero_()
z.grad.data.zero_()

t.backward(z)
print(x.grad)
print(y.grad)

tensor([ 0.0119, -0.6289,  0.0733])
tensor([ 0.0119, -0.6289,  0.0733])
